### ISSUE TITLE
Dynamic Containers

### ISSUE THREAD

**Issue by Looky1173** [Tom-Rawlings/Resizable.js#5]
Hello,

I tried to use this library inside a dynamic container that shares the page with a sidebar. When the sidebar is collapsed, the dimensions of this container change accordingly. Unfortunately, I couldn't get this to work as the dimensions of the parent container are dynamic. Is there a way to fix this?

Thank you for your response in advance!

**Comment by Tom-Rawlings** [comment]
I've updated the code to add a function that resizes the main parent container.

I've also made a branch with a demo page showing how you can get it working with a sidebar.  You basically need to have your sidebar as a separate <div> from the main resizable parent, then call `Resizable.parentResize(window.innerWidth - sidebarWidth, window.innerHeight);` to resize the content when it's opened. You then also need to shift everything over with `document.getElementById("main").style.left = sidebarWidth + 'px';` and of course do the opposite when the sidebar is closed.
This is assuming your sidebar in on the left and the parent of your resizable content has the id of 'main'

https://github.com/Tom-Rawlings/Resizable.js/tree/Sidebar-Demo

Hope this helps

**Comment by Looky1173** [comment]
Thank you for your reply, it helps!
