### ISSUE TITLE
When I modify the size of the windows the content is selected.

### ISSUE THREAD

**Issue by ghost** [Tom-Rawlings/Resizable.js#7]
This happens to me in Firefox.

I'm not sure if I'm doing something wrong, or maybe there is some incompatibility with the web browser. I am using the example configuration.

The problem is that when you drag the resizer the content of the windows is selected and, when I drop it, it is sometimes selected and sometimes not.

Thank you very much for the contribution. It has been very useful!

**Comment by Tom-Rawlings** [comment]
Sorry for the really late reply! This should now be fixed
